# Generated by Django 6.0 on 2025-12-08 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratuvar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isim",
                    models.CharField(max_length=100, verbose_name="Laboratuvar Adı"),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
            ],
        ),
        migrations.CreateModel(
            name="Cihaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isim",
                    models.CharField(
                        max_length=100, verbose_name="Cihaz Adı (Örn: Mikroskop 1)"
                    ),
                ),
                (
                    "aktif_mi",
                    models.BooleanField(
                        default=True, verbose_name="Kullanıma Açık mı?"
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rezervasyon.laboratuvar",
                        verbose_name="Bağlı Olduğu Lab",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Randevu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Randevu Tarihi")),
                ("baslangic_saati", models.TimeField(verbose_name="Başlangıç Saati")),
                ("bitis_saati", models.TimeField(verbose_name="Bitiş Saati")),
                ("olusturulma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "cihaz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rezervasyon.cihaz",
                        verbose_name="Seçilen Cihaz",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Randevuyu Alan",
                    ),
                ),
            ],
        ),
    ]
