# Generated by Django 6.0 on 2025-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cihaz",
            options={"verbose_name": "Cihaz", "verbose_name_plural": "Cihazlar"},
        ),
        migrations.AlterModelOptions(
            name="laboratuvar",
            options={
                "verbose_name": "Laboratuvar",
                "verbose_name_plural": "Laboratuvarlar",
            },
        ),
        migrations.AlterModelOptions(
            name="randevu",
            options={"verbose_name": "Randevu", "verbose_name_plural": "Randevular"},
        ),
        migrations.AddField(
            model_name="randevu",
            name="durum",
            field=models.CharField(
                choices=[
                    ("bekleniyor", "⏳ Bekleniyor"),
                    ("geldi", "✅ Tamamlandı (Geldi)"),
                    ("gelmedi", "❌ Gelmedi (No-Show)"),
                    ("iptal", "🚫 İptal Edildi"),
                ],
                default="bekleniyor",
                max_length=20,
                verbose_name="Randevu Durumu",
            ),
        ),
    ]
