# Generated by Django 6.0 on 2025-12-10 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0002_alter_cihaz_options_alter_laboratuvar_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "okul_numarasi",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Okul Numarası"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefon Numarası"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
