# Generated by Django 6.0 on 2025-12-11 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0003_profil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ariza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aciklama", models.TextField(verbose_name="Arıza Açıklaması")),
                (
                    "cozuldu_mu",
                    models.BooleanField(default=False, verbose_name="Çözüldü mü?"),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Bildirim Tarihi"
                    ),
                ),
                (
                    "cihaz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rezervasyon.cihaz",
                        verbose_name="Arızalı Cihaz",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bildiren Kişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arıza Bildirimi",
                "verbose_name_plural": "Arıza Bildirimleri",
                "ordering": ["-tarih"],
            },
        ),
    ]
