# Generated by Django 6.0 on 2025-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0004_ariza"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Duyuru Başlığı"),
                ),
                (
                    "icerik",
                    models.TextField(
                        blank=True, verbose_name="Duyuru İçeriği (Opsiyonel)"
                    ),
                ),
                (
                    "aktif_mi",
                    models.BooleanField(default=True, verbose_name="Yayında mı?"),
                ),
                ("tarih", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["-tarih"],
            },
        ),
    ]
