# Generated by Django 6.0 on 2025-12-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0005_duyuru"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="resim",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profil_resimleri/",
                verbose_name="Profil Resmi",
            ),
        ),
    ]
