# Generated by Django 6.0 on 2025-12-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0006_profil_resim"),
    ]

    operations = [
        migrations.AddField(
            model_name="cihaz",
            name="aciklama",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="cihaz",
            name="resim",
            field=models.ImageField(
                blank=True, null=True, upload_to="cihazlar/", verbose_name="Cihaz Resmi"
            ),
        ),
    ]
