# Generated by Django 6.0 on 2025-12-20 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0007_cihaz_aciklama_cihaz_resim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profil",
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
        migrations.AddField(
            model_name="profil",
            name="dogrulama_kodu",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="E-Posta Doğrulama Kodu",
            ),
        ),
        migrations.AlterField(
            model_name="profil",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
    ]
