# Generated by Django 6.0 on 2025-12-20 01:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("rezervasyon", "0008_alter_profil_options_profil_dogrulama_kodu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AktifOgrenciler",
            fields=[],
            options={
                "verbose_name": "Aktif Öğrenci",
                "verbose_name_plural": "🟢 Aktif Öğrenciler",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OnayBekleyenler",
            fields=[],
            options={
                "verbose_name": "Onay Bekleyen (Pasif)",
                "verbose_name_plural": "🔴 Onay Bekleyenler",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
