# Generated by Django 6.0 on 2025-12-21 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0009_aktifogrenciler_onaybekleyenler"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="randevu",
            name="onaylayan_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onaylanan_randevular",
                to=settings.AUTH_USER_MODEL,
                verbose_name="İşlemi Yapan Yönetici",
            ),
        ),
        migrations.AlterField(
            model_name="randevu",
            name="durum",
            field=models.CharField(
                choices=[
                    ("onay_bekleniyor", "Onay Bekleniyor"),
                    ("onaylandi", "Onaylandı"),
                    ("reddedildi", "Reddedildi"),
                    ("geldi", "Geldi"),
                    ("gelmedi", "Gelmedi"),
                    ("iptal_edildi", "İptal Edildi"),
                ],
                default="bekleonay_bekleniyor",
                max_length=20,
                verbose_name="Randevu Durumu",
            ),
        ),
    ]
