# Generated by Django 6.0.1 on 2026-02-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rezervasyon", "0010_randevu_onaylayan_admin_alter_randevu_durum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cihaz",
            name="isim",
            field=models.CharField(max_length=100, verbose_name="Cihaz Adı"),
        ),
        migrations.AlterField(
            model_name="duyuru",
            name="icerik",
            field=models.TextField(blank=True, verbose_name="Duyuru İçeriği"),
        ),
        migrations.AlterField(
            model_name="randevu",
            name="cihaz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rezervasyon.cihaz",
                verbose_name="Seçilen Cihaz",
            ),
        ),
        migrations.AlterField(
            model_name="randevu",
            name="durum",
            field=models.CharField(
                choices=[
                    ("onay_bekleniyor", "Onay Bekleniyor"),
                    ("onaylandi", "Onaylandı"),
                    ("reddedildi", "Reddedildi"),
                    ("geldi", "Geldi"),
                    ("gelmedi", "Gelmedi"),
                    ("iptal_edildi", "İptal Edildi"),
                ],
                default="onay_bekleniyor",
                max_length=20,
                verbose_name="Randevu Durumu",
            ),
        ),
    ]
